hello/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.greet, name="greet"),
    path("harshi", views.harshi, name="harshi")
]

newyear/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name = "index")
]

tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"      #to avoid collison of names such as "index" 

urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

testsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls"))
]

hello/models.py
from django.db import models

# Create your models here.

newyear/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def harshi(request):
    return HttpResponse("hello, harshi!")


'''
def greet(request, name):
    return HttpResponse(f"hello, {name.capitalize()}!")
'''

# in order to let html access variarble like name(as key, value pair)
def greet(request, name):
    return render(request, "hello/greet.html", {
        "name": name.capitalize()})

newyear/views.py
import datetime

from django.shortcuts import render

# Create your views here.

def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html",
    {
        "newyear": now.month == 1 and now.day == 1
    })

tasks/views.py
from django import forms
from django.shortcuts import render
from django.http import HttpResponseRedirect    # for redirecting to the page
from django.urls import reverse

# Create your views here.
# from django.http import HttpResponse

# tasks = []    instead of creating a global variable use "sessons" in django

class NewTaskForm(forms.Form):
    task = forms.CharField(label = "New Task")
    # you can add more fields like..
    # priority = forms.IntegerField(label = "Priority", min_value = 1, max_value=10 )

def index(request):
    if "tasks" not in request.session:
        request.session["tasks"]=[]

    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })

def add(request): 
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add.html", {
        "form": form    #exhisting form
}) 

    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
}) 

hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>hello</title>
    </head>
    <body>
        <h1> Heyaaa, {{ name }}! </h1>
    </body>
</html>

hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>hello</title>
    </head>
    <body>
        <h1> Heyaaa world! </h1>
    </body>
</html>

newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE>
<html lang="en">
    <head>
        <title>Is it new year?</title>
        <link href="{% static 'newyear/index.css' %} " rel="stylesheet">
    </head>
    <body>
        {% if newyear %}
            <h1> YES </h1>
        {% else %}    
            <h1> NO </h1>
        {% endif %}
    </body>
</html>

tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
        <h1> Add Task </h1>
        <form action = "{% url "tasks:add" %}" method="post">
        {% csrf_token %}
            {{ form }}
            <input type="submit">
        </form>
    <a href = {% url "tasks:index" %}> View tasks </a> <!--to avoid collison of names such as "index" -->
{% endblock %}   

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
        {% for task in tasks %}     <!-- to plug in a python logic, use these brackets -->
            <li> {{ task }} </li>   <!-- to plug in a value,use these brackets -->
        {% empty %}
            <li> No Tasks </li>
        {% endfor %} 
    <a href = {% url "tasks:add" %}> Add tasks </a>   <!--to avoid collison of names such as "index" -->
{% endblock %}

tasks/templates/tasks/layout.html
<!DOCTYPE>
<html lang="en">
    <head>
        <title>Tasks</title>
    </head>
    <body>
       {% block body %}
       {% endblock %}
    </body>
</html>